services:
  db:
    container_name: quick_queue_db
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      -MYSQL_DATABASE=quick_queue
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:

